version: 2.0
jobs:
  build:
    docker:
      - image: cyw0ng/nutspack-dev:latest
    steps:
      - checkout
      - run:
          name: "Build project"
          command: |
            ./build.sh
      - run:
          name: "Run test cases"
          command: |
            ./runtest.sh
      - run:
          name: Install Testspace client
          command: |
            apt-get install curl -y
            curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C /usr/local/bin
            testspace config url cyw0ng.testspace.com
      - run:
          name: Publish results to Testspace server
          command: |
            testspace .test/*.xml
          when: always